---

- hosts: all
  become: true
  tasks:

  - name: update repository
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache package
    apt: 
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install php support
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install php support
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"
